<?php
DEFINE('NEWS_CT', 'news_article');
DEFINE('NEWS_LINK_FIELD', 'field_news_link');

/**
 * Implements hook_init
 * We are redirecting anything that has the news link values filled out
 */
function slac_news_center_init() {
  $node = menu_get_object();
  if (empty($node)) {
    return;
  }
  // if the news link field is populated, we issue an redirect
  if ($node->type === NEWS_CT) {
    if (!property_exists($node, NEWS_LINK_FIELD)) {
      return;
    }
    if (empty($node->{NEWS_LINK_FIELD})) {
      return;
    }
  }
  $path = $_GET['q'];
  $path_components = explode('/', $path);
  // we don't redirect for path such as node/[nid]/edit
  if (count($path_components) > 2) {
    return;
  }
  if (isset($node->{NEWS_LINK_FIELD}[LANGUAGE_NONE][0]['url'])) {
    $url = $node->{NEWS_LINK_FIELD}[LANGUAGE_NONE][0]['url'];
    drupal_goto($url, array(), 301);
    drupal_exit();
  }
}

/**
 * Implements hook_node_view
 */
function slac_news_center_node_view($node, $view_mode) {

  // adding promoted into a rss category
  if ($view_mode === 'rss') {
    if ($node->promote == 1) {
      $node->rss_elements[] = array(
        'key' => 'category',
        'value' => 'Promoted',
      );
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function slac_news_center_field_formatter_info() {
  return array(
    'image_rss_enclosure' => array(
      'label' => t('RSS Enclosure'),
      'field types' => array('image'),
      'settings' => array(
          'image_style' => '',
        ),
    ),
  );
}

/**
 * Settings form
 */
function slac_news_center_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $image_styles = image_style_options(FALSE);
  $element['image_style'] = array(
    '#title' => t('Image style'),
    '#type' => 'select',
    '#default_value' => $settings['image_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function slac_news_center_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  $image_styles = image_style_options(FALSE);
  // Unset possible 'No defined styles' option.
  unset($image_styles['']);
  // Styles could be lost because of enabled/disabled modules that defines
  // their styles in code.
  if (isset($image_styles[$settings['image_style']])) {
    $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
  }
  else {
    $summary[] = t('Original image');
  }

  return implode('<br />', $summary);
}


/**
 * Implements hook_field_formatter_view().
 */
function slac_news_center_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'image_rss_enclosure':
      foreach ($items as $delta => $item) {
        $entity->rss_elements[] = array(
          'key' => 'enclosure',
          'attributes' => array(
            'url' => (($display['settings']['image_style']) != '') ? image_style_url($display['settings']['image_style'], $item['uri']) : file_create_url($item['uri']),
            // 'url' => $display['settings']['image_style'],
            'type' => (isset($item['filemime'])) ? $item['filemime'] : '',
            'length' => (isset($item['filesize'])) ? $item['filesize'] : 0,
          ),
        );
      }
    break;
  }
  return $element;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_news_center_ctools_plugin_directory($module, $plugin) {
  if ($module === 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function slac_news_center_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_views_pre_build().
 */
function slac_news_center_views_pre_build(&$view) {
  $path = current_path();
  $arguments = explode('/', $path);

  if ($arguments['0'] != 'news' || !isset($arguments['1']) || $view->name != 'news_center') {
    return;
  }

  $archive_type = substr($arguments['1'], 0, -5);
  $year = substr($arguments['1'], -4);

  if ($archive_type == 'news-feature-archive' && is_numeric($year)) {
    $title = $year . ' ' . t('News Feature Archive');
    drupal_set_title($title);
  }
  elseif ($archive_type == 'press-release-archive' && is_numeric($year)) {
    $title = $year . ' ' . t('Press Release Archive');
    drupal_set_title($title);
  }
}

/**
* Implements hook_entity_info_alter().
*/
function slac_news_center_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['news_center'] = array(
    'label' => t('News Center'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['page_full'] = array(
    'label' => t('Page Full'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['header_cropped'] = array(
    'label' => t('Header Cropped'),
    'custom settings' => TRUE,
  );
}
