<?php

/**
 * Implements hook_node_view
 */
function slac_news_center_node_view($node, $view_mode) {
  // adding promoted into a rss category
  if ($view_mode === 'rss') {
    if ($node->promote == 1) {
      $node->rss_elements[] = array(
        'key' => 'category',
        'value' => 'Promoted',
      );
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function slac_news_center_field_formatter_info() {
  return array(
    'image_rss_enclosure' => array(
      'label' => t('RSS Enclosure'),
      'field types' => array('image'),
    ),
  );
} 

/**
 * Implements hook_field_formatter_view().
 */
function slac_news_center_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'image_rss_enclosure':
      foreach ($items as $delta => $item) {
        $entity->rss_elements[] = array(
          'key' => 'enclosure',
          'attributes' => array(
            'url' => file_create_url($item['uri']),
            'type' => (isset($item['filemime'])) ? $item['filemime'] : '',
            'length' => (isset($item['filesize'])) ? $item['filesize'] : 0,
          ),
        );      
      }
    break;
  }
  return $element;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_news_center_ctools_plugin_directory($module, $plugin) {
  if ($module === 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function slac_news_center_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_views_pre_build().
 */
function slac_news_center_views_pre_build(&$view) {
  $path = current_path();
  $arguments = explode('/', $path);

  if ($arguments['0'] != 'news' || !isset($arguments['1']) || $view->name != 'news_center') {
    return;
  }

  $archive_type = substr($arguments['1'], 0, -5);
  $year = substr($arguments['1'], -4);

  if ($archive_type == 'news-feature-archive' && is_numeric($year)) {
    $title = $year . ' ' . t('News Feature Archive');
    drupal_set_title($title);
  }
  elseif ($archive_type == 'press-release-archive' && is_numeric($year)) {
    $title = $year . ' ' . t('Press Release Archive');
    drupal_set_title($title);
  }
}
