<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function slac_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor != 'ckeditor') {
    return;
  }

  // Remove "Insert paragraph here" plugin.
  // @see http://ckeditor.com/forums/CKEditor/How-to-Remove-Insert-Paragraph-Here-Pointer
  $settings['removePlugins'] = 'magicline';
}