<?php

/**
 * Implements hook_ctools_plugin_dierctory()
 */
function slac_frontpage_slideshow_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_views_api().
 */
function slac_frontpage_slideshow_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'slac_frontpage_slideshow') . '/plugins/views',
  );
}

/**
 * Implements hook_preprocess_views_view_field
 * Added inline css
 * @param string $vars
 * @param type $hook 
 */
function slac_frontpage_slideshow_preprocess_views_view_field(&$vars, $hook) {
  if ($vars['field']->view->name == 'frontpage_slideshow' && $vars['field']->real_field == 'nothing') {
    $style = explode(PHP_EOL, $vars['view']->display['panel_slideshow_pane_1']->display_options['pane_conf']['slideshow_configuration']);
    $slide_count = &drupal_static(__FUNCTION__ . ':slide_count', 0);
    if (isset($style[$slide_count])) {
      list($position, $color) = explode(',', $style[$slide_count]);
      $vars['output'] = '<div class="slide-text-side" style="' . (($color) ? 'background-color:' . $color . ';' : '') . ' ' . (($position) ? 'float: ' . $position : '') . '">' . $vars['output'] . '</div>';
    }
    else {
      $vars['output'] = '<div class="slide-text-side" >' . $vars['output'] . '</div>';
    }
    $slide_count++;
  }
}