<?php

/**
 * Implements hook_form_alter
 * @param type $form
 * @param type $form_state
 * @param type $form_id 
 */
function slac_forms_alter_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'webform_client_form') !== false) {
    if ($form['#node']->field_form_page[LANGUAGE_NONE][0]['value'] == 'send_us_your_feedback') {
      $form['actions']['submit']['#value'] = t('» send feedback');
    }
  }
}

/**
 * Implements template_preprocess_node
 * @param array $variables 
 */
function slac_forms_alter_preprocess_node(&$variables) {
  if (isset($variables['field_form_page']) && $variables['field_form_page'][LANGUAGE_NONE][0]['value'] == 'send_us_your_feedback') {
    $variables['content']['webform']['#form']['submitted']['topic_of_your_feedback___question']['#options'][''] = t('Please make a selection');
  }
}