<?php

/**
 * Implements hook_form_alter
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function slac_forms_alter_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id = 'page_node_form' && isset($form['field_related_links'])) {
    $form['field_related_links']['#suffix'] = '<div class="new-rl-block"><span>'
      . l('Create new Related links block', 'admin/structure/fieldable-panels-panes/manage/related-links/add') . '</span></div>';
  }

  if (strpos($form_id, 'webform_client_form') !== FALSE) {
    if (isset($form['#node']->field_form_page) && !empty($form['#node']->field_form_page) && $form['#node']->field_form_page[LANGUAGE_NONE][0]['value'] == 'send_us_your_feedback') {
      $form['actions']['submit']['#value'] = t('» send feedback');
    }
  }
  // add pleceholder to search box
  if ($form_id == 'search_block_search_form') {
    $form['keyword']['#attributes'] = array('placeholder' => t('search web or people'));
  }
}

/**
 * Implements template_preprocess_node
 * @param array $variables
 */
function slac_forms_alter_preprocess_node(&$variables) {
  if (isset($variables['field_form_page']) && !empty($variables['field_form_page']) && $variables['field_form_page'][LANGUAGE_NONE][0]['value'] == 'send_us_your_feedback') {
    $variables['content']['webform']['#form']['submitted']['topic_of_your_feedback___question']['#options'][''] = t('Please make a selection');
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function slac_forms_alter_field_widget_form_alter(&$element, &$form_state, $context) {
  $instance = $context['instance'];
  $settings = $instance['settings'];

  if (isset($settings['image_field_caption']) && $instance['widget']['type'] == 'image_image' && $settings['image_field_caption']) {
    foreach (element_children($element) as $delta) {
      $element[$delta]['#process'][] = 'slac_forms_alter_widget_process';
    }
  }
}

/**
 * Callback function to alter 'image_field_caption' field.
 */
function slac_forms_alter_widget_process($element, &$form_state, $form) {
  $item = $element['#value'];

  if (isset($element['image_field_caption'])) {
    $element['image_field_caption']['#title'] = t('Description');
    $element['image_field_caption']['#resizable'] = FALSE;
    $element['image_field_caption']['#weight'] = 0;
    $element['image_field_caption']['#description'] = t('The description contains additional information about the image.');
    $element['image_field_caption']['#format'] = 'plain_text';
  }

  return $element;
}

/**
 * Implements hook_element_info_alter()
 */
function slac_forms_alter_element_info_alter(&$type) {
  if (isset($type['link_field'])) {
    $type['link_field']['#process'][] = 'slac_forms_alter_link_field_process';
  }
}

function slac_forms_alter_link_field_process($element, $form_state, $complete_form) {
  switch ($element['#field_name']) {
    case 'field_link':
      $element['title']['#title'] = t('Source');
      break;
  }

  return $element;
}
