<?php
/**
 * @file
 * Code for the SLAC External Email feature.
 */

include_once 'slac_external_email.features.inc';

/**
 * Implements hook_node_view_alter
 */
function slac_external_email_node_view_alter(&$build) {
  if ($build['#bundle'] == 'news_article') {
    if ($build['#view_mode'] == 'email_side_news' ||
      $build['#view_mode'] == 'email_top_story' ||
      $build['#view_mode'] == 'email_main_story') {
      unset($build['links']);
      unset($build['#contextual_links']);
    }
  }
}

/**
 * Implements hook_mailchimp_dc_content
 */
function slac_external_email_mailchimp_dc_content($template_sections = array()) {
  
  // declare contents in the daily digest  
  $data['SLAC_EXT'] = array(
    'module' => 'slac_external_email',
    'title' => t('SLAC external email'),
    'content' => _slac_external_email_mailchimp_dc_content($template_sections),
  );
  return $data;
}

/**
 * Output contents
 */
function _slac_external_email_mailchimp_dc_content($template_sections) {
  return array(
    'html_top_stories' => array(
      'value' => views_embed_view('email_top_stories', 'panel_pane_2'),
      'format' => 'mailchimp_campaign',
    ),
  );  
}

