<?php

/**
 * Implements hook_file_mimetype_mapping_alter().
 *
 * Regster the video/youtube mimetype.
 */
function media_youtube_customization_mimetype_mapping_alter(&$mapping) {
  $mapping['mimetypes'][] = 'video/youtube';
}

/*
 * Implements hook_file_default_types_alter().
 *
 * Adds the video/youtube fake mimetype to video files.
 */

function media_youtube_customization_default_types_alter(&$types) {
  $types['video']->mimetypes[] = 'video/youtube';
}

/**
 * Implements hook_field_formatter_info().
 */
function media_youtube_customization_field_formatter_info() {
  return array(
    'media_youtube_video_popup' => array(
      'label' => t('Youtube Video popup'),
      'field types' => array('file'),
      'settings' => array(
        'file_view_mode' => 'default',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function media_youtube_customization_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'media_youtube_video_popup':
      // Spoof the file_rendered formatter.
      $display['type'] = 'file_rendered';
      foreach ($items as $delta => $item) {
        if ($item['type'] == 'video') {
          // Transform the stream wrapper into a path.
          $path = drupal_realpath($item['uri']);

          // Parse the URL into parts, in order to make it an embed URL.
          // Make sure the correct include file is loaded
          module_load_include('inc', 'media_youtube', '/includes/media_youtube.formatters.inc');

          // Load the file
          $file = file_load($item['fid']);

          // Set up the settings array with your image style
          $display['settings'] = array('image_style' => 'medium');

          // Get the render array for the thumbnail image
          $image_render_array = media_youtube_file_formatter_image_view($file, $display, LANGUAGE_NONE);

          // Wrap the image in a link to trigger lightbox.
          $render_video = array(
            '#type' => 'link',
            '#title' => render($image_render_array),
            '#href' => $path,
            '#options' => array(
              'html' => TRUE,
              'attributes' => array(
                'class' => array(
                  'lightbox',
                  'youtube-thumbnail'
                ),
                'rel' => array('lightvideo'),
              ),
            ),
          );
          // Wrap the title in a link to trigger lightbox.
          $title = array(
            '#type' => 'link',
            '#title' => $item['field_title'][LANGUAGE_NONE][0]['value'],
            '#href' => $path,
            '#options' => array(
              'html' => TRUE,
              'attributes' => array(
                'class' => array(
                  'lightbox',
                  'youtube-title'
                ),
                'rel' => array('lightvideo'),
              ),
            ),
          );
        }

        $render_element['video'] = $render_video;
        $render_element['title'] = $title;

        $element[$delta] = array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'youtube-video-popup',
            ),
          ),
          'item' => $render_element,
        );
      }
      break;
  }

  return $element;
}