<?php

/**
 * Implemanted hook_form_alter()
 *
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function slac_site_variables_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_information']['employee_portal_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Employee Portal url'),
      '#description' => t('This url is used in the header.'),
      '#default_value' => variable_get('employee_portal_url', ''),
    );
    $form['site_information']['research_resources_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Research Resources url'),
      '#description' => t('This url is used in the header.'),
      '#default_value' => variable_get('research_resources_url', ''),
    );
    $form['#submit'][] = 'slac_site_variables_form_submit';
  }
}

/**
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_submit(&$form, &$form_state) {
  variable_set('employee_portal_url', $form_state['values']['employee_portal_url']);
  variable_set('research_resources_url', $form_state['values']['research_resources_url']);
}

/**
 * Implemented hook_form_system_theme_settings_alter()
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_system_theme_settings_alter(&$form, &$form_state) {
  $form['theme_settings']['employee_portal_url'] = array(
    '#type' => 'checkbox',
    '#title' => t('Employee Portal url'),
    '#default_value' => theme_get_setting('employee_portal_url'),
  );
  $form['theme_settings']['research_resources_url'] = array(
    '#type' => 'checkbox',
    '#title' => t('Employee Portal url'),
    '#default_value' => theme_get_setting('research_resources_url'),
  );
}

