<?php

/**
 * Implemanted hook_form_alter()
 *
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function slac_site_variables_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_information']['employee_portal_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Employee Portal url'),
      '#description' => t('This address is used by link from header.'),
      '#default_value' => variable_get('employee_portal_url', ''),
    );
    $form['#submit'][] = 'slac_site_variables_form_submit';
  }
}

/**
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_submit(&$form, &$form_state) {
  variable_set('employee_portal_url', $form_state['values']['employee_portal_url']);
}

/**
 * Implemented hook_form_system_theme_settings_alter()
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_system_theme_settings_alter(&$form, &$form_state) {
  $form['theme_settings']['employee_portal_url'] = array(
    '#type' => 'checkbox',
    '#title' => t('Employee Portal url'),
    '#default_value' => theme_get_setting('employee_portal_url'),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_site_variables_ctools_plugin_directory($owner, $plugin) {
  if ($owner === 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function slac_site_variables_ctools_plugin_api($module, $api) {
  if ($module == 'slac_site_variables') {
    return array('version' => 1);
  }
}
