<?php

/**
 * @file
 * Features Annoyment - basic API functions and hook implementations.
 */

/**
 * Implements hook_permission().
 */
function features_annoyment_permission() {
  return array(
    'hide features annoyment warning' => array(
      'title' => t('Hide features annoyment warning'),
      'description' => t('Hiding the warning from features annoyment if one or 
                          more features are not in default state.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_init().
 */
function features_annoyment_init() {
  global $user;
  
  if ($user->uid > 0 && ($user->uid == 1 || !user_access('hide features annoyment warning'))) {
    module_load_include('inc', 'features', 'features.export');
    $features = features_get_features();
    
    $overwritten = FALSE;
    foreach ($features as $key => $feature) {
      if ($feature->status) {
        $storage = features_get_storage($key);
        if ($storage) {
          $overwritten = TRUE;
          break;
        }
      }
    }
    
    drupal_set_message(t('One or more features are not in default state! !details', 
        array('!details' => l(t('See details in the features administration.'), 'admin/structure/features'))), 'error', FALSE);
  }
}