<?php

/**
 * Implementation of hook_menu
 * @return string 
 */
function slac_public_lectures_menu() {
  $items['admin/content/scheduled-lecture'] = array(
    'title' => 'Scheduler lecture',
    'access arguments' => array('administer content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slac_public_lectures_form'),
  );
  return $items;
}

/**
 * Admin page
 * @return string 
 */
function slac_public_lectures_form() {

  $form['textarea'] = array(
    '#type' => 'text_format',
    '#title' => t('Scheduler lecture'),
    '#description' => t('Details of next public lecture.'),
    '#default_value' => variable_get('public_lecture_dscription', ''),
    '#weight' => 0,
  );
  $form['display'] = array(
    '#type' => 'checkbox',
    '#title' => t("Check to display next lecture date on 'SLAC Public Lecture Series' page"),
    '#default_value' => variable_get('public_lecture_display', 0),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  return $form;
}

function slac_public_lectures_form_submit($form, &$form_state) {
  variable_set('public_lecture_dscription', $form_state['values']['textarea']['value']);
  variable_set('public_lecture_display', $form_state['values']['display']);
}

/**
 * Implements hook_block_info().
 */
function slac_public_lectures_block_info() {
  $blocks['scheduled_lecture_block'] = array(
    'info' => t('Scheduler Lecture'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function slac_public_lectures_block_view($delta) {
  switch ($delta) {
    case 'scheduled_lecture_block':
      $block['subject'] = '';
      $block['content'] = variable_get('public_lecture_dscription', '');
      return $block;
      break;
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to look for the .inc file that
 * defines various args, contexts and content_types.
 */
function slac_public_lectures_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
