<?php

/**
 * Implements hook_entity_view_alter().
 *
 * Switch video links to https:// so they can be viewed if page loaded under https://.
 * Otherwise modern browsers block that content.
 * @see http://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire
 */
function slac_video_fpp_entity_view_alter(&$build, $type) {
  if ($type != 'fieldable_panels_pane' || $build['#bundle'] != 'fieldable_panels_pane') {
    return;
  }
  foreach (element_children($build['field_multimedia']) as $key) {
    $build['field_multimedia'][$key]['file']['item']['video']['#href'] = str_replace('http://', 'https://', $build['field_multimedia'][$key]['file']['item']['video']['#href']);
  }
}