<?php
/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function pp_bi_menu() {
  $items = array();

  $type = 'pp_bi';
  $types = bean_get_types();
  $type = $types[$type];

  $items['block/add/' . str_replace('_', '-', $type->type) . '/%ctools_js'] = array(
    'title' => 'zzz',
    'title callback' => 'check_plain',
    'page callback' => 'pp_bi_block_add',
    //'page arguments' => array($type->type, 3),
    'access arguments' => array('create any ' . $type->type . ' bean'),
    'description' => $type->getDescription(),
    'file' => 'pp_bi.pages.inc',
  );

  /*$items['modal/node/%node/edit/%ctools_js/%'] = array(
    'title' => 'Edit',
    'page callback' => 'edit_node_modal_node_page_edit',
    'page arguments' => array(2, 4, 5),
    'access callback' => 'node_access',
    'access arguments' => array('update', 2),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'pp_bi.pages.inc',
  );*/

  return $items;
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function pp_bi_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/**
 * Implements hook_bean_types_api_info().
 */
function pp_bi_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function pp_bi_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'pp_bi') . '/plugins/bean';
  $plugins['pp_bi'] = array(
    'label' => t('PP Block'),
    'description' => t('Block created by PP Block Insert module.'),
    'handler' => array(
      'class' => 'BlockBean',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'pp_bi.block.inc',
  );
  $plugins['pp_bi_2'] = array(
    'label' => t('PP Block 2'),
    'description' => t('Block created by Bean module.'),
    'handler' => array(
      'class' => 'BlockBean',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'pp_bi.block.inc',
  );
  return $plugins;
}

/**
 * Implements hook_theme().
 */
function pp_bi_theme() {
  $items = array();
  $items['pp_bi_settings'] = array(
    'arguments' => array(
      'records_shown' => NULL,
    ),
    'file' => 'pp_bi.theme.inc',
  );
  $items['pp_bi_more_link'] = array(
    'arguments' => array(
      'text' => NULL,
      'path'  => NULL,
    ),
    'file' => 'pp_bi.theme.inc',
  );
  return $items;
}
