<?php

/**
 * Implements hook_entity_info_alter().
 */
function slac_related_links_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['related_links'] = array(
    'label' => t('Related Links'),
    'pane category' => t('SLAC panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/related-links',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function slac_related_links_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'fieldable_panels_panes_entity_edit_form'
    && isset($form['#entity']->bundle)
    && isset($form['reusable']['admin_title'])) {
    if ($form['#entity']->bundle == 'related_links') {
      $form['reusable']['admin_title']['#required'] = TRUE;
    }
  }
}


/**
 * Implements hook_contextual_links_view_alter().
 */
function slac_related_links_contextual_links_view_alter(&$element, $items) {
  $links = array();
  if (isset($element['#element']['#entity_type'])
    && $element['#element']['#entity_type'] == 'fieldable_panels_pane'
    && $element['#element']['#bundle'] == 'related_links') {
    $links['edit-regex'] = array(
      'title' => t('Edit int/ext icons rules'),
      'href' => 'admin/config/user-interface/int-ext-links',
      'query' => drupal_get_destination(),
    );
    $links = $links + $element['#links'];
    $element['#links'] = $links;
  }
}
