<?php

/**
 * Implements hook_entity_info_alter().
 */
function slac_related_links_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['related_links'] = array(
    'label' => t('Related Links'),
    'pane category' => t('SLAC panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/related-links',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}