<?php
/**
 * @file
 * slac_beans.bean.inc
 */

/**
 * Implements hook_bean_admin_ui_types().
 */
function slac_beans_bean_admin_ui_types() {
  $export = array();

  $bean_type = new stdClass();
  $bean_type->disabled = FALSE; /* Edit this to true to make a default bean_type disabled initially */
  $bean_type->api_version = 5;
  $bean_type->name = 'image_text_link';
  $bean_type->label = 'Image, text, link';
  $bean_type->options = '';
  $bean_type->description = '';
  $export['image_text_link'] = $bean_type;

  return $export;
}
