<?php
/**
 * @file
 * Code for the slac_beans feature.
 */

include_once 'slac_beans.features.inc';

/**
 * Implements hook_entity_view_alter().
 */
function slac_beans_entity_view_alter(&$build, $type) {
  if ($type != 'bean') {
    return;
  }
  if ($build['#bundle'] == 'image_text_link') {
    $build['#theme'] = 'slac_beans_image_text_link';
  }
  if ($build['#bundle'] == 'block_with_brochures') {
    $build['#theme'] = 'slac_beans_block_with_brochures';
  }
  if ($build['#bundle'] == 'shaded_no_title_block') {
    $build['#theme'] = 'slac_beans_shaded_no_title_block';
  }
  if ($build['#bundle'] == 'summary_block') {
    $build['#theme'] = 'slac_beans_summary_block';
  }
}

/**
 * Implements hook_theme().
 */
function slac_beans_theme() {
  return array(
    'slac_beans_image_text_link' => array(
      'render element' => 'entity',
      'template' => 'slac_beans_image_text_link',
    ),
    'slac_beans_block_with_brochures' => array(
      'render element' => 'entity',
      'template' => 'slac_beans_block_with_brochures',
    ),
    'slac_beans_shaded_no_title_block' => array(
      'render element' => 'entity',
      'template' => 'slac_beans_shaded_no_title_block',
    ),
    'slac_beans_summary_block' => array(
      'render element' => 'entity',
      'template' => 'slac_beans_summary_block',
    ),
  );
}

/**
 * Preprocess function for slac_beans_block_with_brochures.tpl.php template.
 */
function slac_beans_preprocess_slac_beans_block_with_brochures(&$vars) {
  $item_values = array();

  foreach (element_children($vars['entity']['field_block_bb_content']) as $key) {
    foreach ($vars['entity']['field_block_bb_content'][$key]['entity']['field_collection_item'] as $item) {
      foreach (element_children($item['field_block_bb_brochures']) as $bb_key) {
        foreach ($item['field_block_bb_brochures'][$bb_key]['entity']['field_collection_item'] as $bb_item) {
          $image_alt = '';
          if (isset($bb_item['field_brochure_image'][0]['#item']['field_file_image_alt_text'][LANGUAGE_NONE][0]['value'])) {
            $image_alt = $bb_item['field_brochure_image'][0]['#item']['field_file_image_alt_text'][LANGUAGE_NONE][0]['value'];
          }
          $image_title = '';
          if (isset($bb_item['field_brochure_image'][0]['#item']['field_file_image_title_text'][LANGUAGE_NONE][0]['value'])) {
            $image_title = $bb_item['field_brochure_image'][0]['#item']['field_file_image_title_text'][LANGUAGE_NONE][0]['value'];
          }
          $brochure_items[] = array(
            'image' => drupal_render($bb_item['field_brochure_image'][0]),
            'image_alt' => $image_alt,
            'image_title' => $image_title,
            'title' => $bb_item['field_brochure_title'][0]['#markup'],
            'link' => drupal_render($bb_item['field_brochure_download_link'][0]),
            'url' => $bb_item['field_brochure_download_link']['#items'][0]['url'],
          );
        }
      }
      $item_values[] = array(
        'title' => $item['field_block_bb_title'][0]['#markup'],
        'brochure_items' => $brochure_items,
      );
    }
  }

  $vars['blocks'] = $item_values;

  static $once;
  if (!$once) {
    $once = TRUE;
  }
}

/**
 * Preprocess function for slac_beans_image_text_link.tpl.php template.
 */
function slac_beans_preprocess_slac_beans_image_text_link(&$vars) {

  dpm($vars);

  $item_values = array();
  foreach (element_children($vars['entity']['field_block_itl_content']) as $key) {
    foreach ($vars['entity']['field_block_itl_content'][$key]['entity']['field_collection_item'] as $item) {
      $shaded_background = FALSE;
      if (isset($item['field_block_itl_background']['#items'][0]['value'])) {
        $shaded_background = $item['field_block_itl_background']['#items'][0]['value'];
      }
      $url = '';
      if (isset($item['field_block_itl_link']['#items'][0]['url'])) {
        $url = $item['field_block_itl_link']['#items'][0]['url'];
      }
      $item_values[] = array(
        'title' => $item['field_block_itl_title'][0]['#markup'],
        'text' => $item['field_block_itl_text'][0]['#markup'],
        'image' => drupal_render($item['field_block_itl_image'][0]['file']),
        'link' => drupal_render($item['field_block_itl_link'][0]),
        'url' => $url,
        'shaded_background' => $shaded_background,
      );
    }
  }

  $vars['blocks'] = $item_values;

  static $once;
  if (!$once) {
    $once = TRUE;
  }
}

/**
 * Preprocess function for slac_beans_shaded_no_title_block.tpl.php template.
 */
function slac_beans_preprocess_slac_beans_shaded_no_title_block(&$vars) {
  $item_values = array();
  foreach (element_children($vars['entity']['field_block_no_title']) as $key) {
    foreach ($vars['entity']['field_block_no_title'][$key]['entity']['field_collection_item'] as $item) {
      $title = '';
      if (isset($item['field_block_no_title_title'][0]['#markup'])) {
        $title = $item['field_block_no_title_title'][0]['#markup'];
        }
      $item_values[] = array(
        'title' => $title,
        'text' => $item['field_block_no_title_body'][0]['#markup'],
      );
    }
  }

  $vars['blocks'] = $item_values;

  static $once;
  if (!$once) {
    $once = TRUE;
  }
}

/**
 * Preprocess function for slac_beans_image_text_link.tpl.php template.
 */
function slac_beans_preprocess_slac_beans_summary_block(&$vars) {
  $item_values = array();
  foreach (element_children($vars['entity']['field_block_itl_content']) as $key) {
    foreach ($vars['entity']['field_block_itl_content'][$key]['entity']['field_collection_item'] as $item) {
      $shaded_background = FALSE;
      if (isset($item['field_block_itl_background']['#items'][0]['value'])) {
        $shaded_background = $item['field_block_itl_background']['#items'][0]['value'];
      }
      $url = '';
      if (isset($item['field_block_itl_link']['#items'][0]['url'])) {
        $url = $item['field_block_itl_link']['#items'][0]['url'];
      }
      $item_values[] = array(
        'title' => $item['field_block_itl_title'][0]['#markup'],
        'text' => $item['field_block_itl_text'][0]['#markup'],
        'image' => drupal_render($item['field_block_itl_image'][0]['file']),
        'link' => drupal_render($item['field_block_itl_link'][0]),
        'url' => $url,
        'shaded_background' => $shaded_background,
      );
    }
  }

  $vars['blocks'] = $item_values;

  static $once;
  if (!$once) {
    $once = TRUE;
  }
}
