<?php

/**
 * Implements hook_entity_info_alter().
 */
function slac_events_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['events'] = array(
    'label' => t('Events'),
    'pane category' => t('SLAC panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/events',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
  $entity_info['fieldable_panels_pane']['uri callback'] = 'slac_events_fpp_uri_callback';
}

/**
 * Set the URL of the event fpp so on frontpage we can link image of event fpp to its link.
 */
function slac_events_fpp_uri_callback($fpp) {
  if ($fpp->bundle == 'events') {
    return array('path' => $fpp->field_link[LANGUAGE_NONE][0]['url']);
  }
}
