<?php

/**
 * Implements hook_contextual_links_view_alter().
 *
 * Add "Edit slideshow content" for frontpage slideshow contextual links.
 */
function slac_admin_contextual_links_view_alter(&$element, $items) {
  if (_slac_admin_is_contextual_link_a_view($element, 'frontpage_slideshow')) {
    $element['#links']['edit-content'] = array(
      'title' => t('Edit slideshow content'),
      'href' => 'admin/structure/fieldable-panels-panes/manage/slideshow',
      'query' => $element['#links']['views-ui-edit']['query'],
    );
  }

  if (_slac_admin_is_contextual_link_a_view($element, 'slac_in_the_news')) {
    $element['#links']['edit-content'] = array(
      'title' => t('Edit listed content'),
      'href' => 'admin/structure/in_the_news',
    );
  }
}

/**
 * Helper function for contextual links.
 */
function _slac_admin_is_contextual_link_a_view($element, $view_id) {
  return isset($element['#links']['views-ui-edit']['href']) && $element['#links']['views-ui-edit']['href'] == 'admin/structure/views/view/' . $view_id . '/edit';
}

/**
 * Implementation of hook_views_api().
 */
function slac_admin_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'slac_admin'),
  );
}
