<?php
/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function bean_wysiwyg_menu() {
  $items = array();

  $items['bean_wysiwyg/block/%'] = array(
    'title' => 'Form to add/edit a block',
    'page callback' => 'bean_wysiwyg_block_page',
    'page arguments' => array(2),
    'access arguments' => array('use block insert'),
    'description' => 'Callback to create or edit a block',
    'theme callback' => 'media_dialog_get_theme_name',
    'file' => 'bean_wysiwyg.pages.inc',
  );

  $items['bean_wysiwyg/browser'] = array(
    'title' => 'Block insert browser',
    'description' => 'Browser to select the type of the block to insert',
    'page callback' => 'bean_wysiwyg_browser',
    'access arguments' => array('use block insert'),
    'type' => MENU_CALLBACK,
    'theme callback' => 'media_dialog_get_theme_name',
    'file' => 'bean_wysiwyg.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bean_wysiwyg_permission() {
  return array(
    'use block insert' => array(
      'title' => t('Use blocks insert functionality'),
      'description' => t('Use blocks insert functionality'),
    ),
  );
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function bean_wysiwyg_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/**
 * Implements hook_bean_types_api_info().
 */
function bean_wysiwyg_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_theme().
 */
function bean_wysiwyg_theme() {
  $items = array();
  $items['bean_wysiwyg_settings'] = array(
    'arguments' => array(
      'records_shown' => NULL,
    ),
    'file' => 'bean_wysiwyg.theme.inc',
  );
  $items['bean_wysiwyg_more_link'] = array(
    'arguments' => array(
      'text' => NULL,
      'path'  => NULL,
    ),
    'file' => 'bean_wysiwyg.theme.inc',
  );
  return $items;
}

/**
 * Implements hook_library().
 */
function bean_wysiwyg_library() {
  $libraries = array();

  $libraries['bean_wysiwyg_browser'] = array(
    'title' => 'Block Insert popup libraries',
    'js' => array(
      drupal_get_path('module', 'bean_wysiwyg') . '/js/bean_wysiwyg.popups.js' => array('group' => JS_DEFAULT),
    ),
    'dependencies' => array(
      array('media', 'media_base'),
      array('system', 'ui.resizable'),
      array('system', 'ui.draggable'),
      array('system', 'ui.dialog'),
    ),
    'version' => '1.0',
  );

  return $libraries;
}

/**
 * Default settings of the javascripts.
 */
function bean_wysiwyg_browser_js() {
  $settings = array(
    'browserUrl' => url('bean_wysiwyg/browser',
      array('query' => array('render' => 'block_types'))),
    'browserUpdateBlockUrl' => url('bean_wysiwyg/block/'),
  );

  $js = array(
    'library' => array(
      array('bean_wysiwyg', 'bean_wysiwyg_browser'),
    ),
    'js' => array(
      array(
       'data' => array('bean_wysiwyg' => $settings),
       'type' => 'setting',
      ),
    ),
  );
  return $js;
}

/**
 * Implements hook_admin_paths().
 */
function bean_wysiwyg_admin_paths() {
  $paths['bean_wysiwyg/*'] = TRUE;
  return $paths;
}

/**
 * Alter bean_form form.
 */
function bean_wysiwyg_form_bean_form_alter(&$form, $form_state) {
  // We pass 'ajax' argument in bean_wysiwyg_block_page().
  if (!in_array('ajax', $form_state['build_info']['args'])) {
    return;
  }

  $form['#attached']['js'] = array(drupal_get_path('module', 'bean_wysiwyg') . '/js/bean_wysiwyg.iframe.js');
  $form['actions']['submit']['#ajax'] = array( 'callback' => 'bean_form_ajax_callback',);
}

function bean_form_ajax_callback($form, $form_state) {
  $commands = array();
  $bean = $form_state['bean'];
  $build = bean_view($bean);
  _bean_wysiwyg_strip_contextual_links($build);
  $commands[] = ajax_command_invoke('body', 'blockSelectDialogFinalizeSelection', array(
    array('bid' => $bean->bid, 'html' => drupal_render($build)),
  ));
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_filter_info().
 */
function bean_wysiwyg_filter_info() {
  $filters['bean_wysiwyg_filter'] = array(
    'title' => t('Convert Block Insert tags to markup'),
    'description' => t('This filter will convert [block_insert]...[/block_insert] tags into markup.'),
    'process callback' => 'bean_wysiwyg_filter_process',
    'weight' => 2,
  );

  return $filters;
}

/**
 * Finds all matches and run them through bean_wysiwyg_token_to_markup().
 */
function bean_wysiwyg_filter_process($text) {
  $text = ' ' . $text . ' ';
  $text = preg_replace_callback("/\[block_insert\].*?\[\/block_insert\]/s", 'bean_wysiwyg_token_to_markup', $text);

  return $text;
}

/**
 * Convert tokens to markup.
 */
function bean_wysiwyg_token_to_markup($match) {
  $bean_bid = substr($match[0], strlen('[block_insert]'), strlen($match[0]) - strlen('[block_insert]') - strlen('[/block_insert]'));
  $bean = bean_load($bean_bid);
  $build = bean_view($bean);
  _bean_wysiwyg_strip_contextual_links($build);
  return drupal_render($build);
}

/**
 * Implements hook_element_info_alter().
 */
function bean_wysiwyg_element_info_alter(&$types) {
  $types['text_format']['#pre_render'][] = 'bean_wysiwyg_pre_render_text_format';
}

function bean_wysiwyg_pre_render_text_format($element) {
  // filter_process_format() copies properties to the expanded 'value' child
  // element.
  if (!isset($element['format'])) {
    return $element;
  }

  $field = &$element['value'];

  $tagmap = _bean_wysiwyg_generate_tagMap($field['#value']);

  if (isset($tagmap)) {
    drupal_add_js(array('bean_wysiwyg_tagmap' => $tagmap), 'setting');
  }
  return $element;
}

function _bean_wysiwyg_generate_tagMap($text) {
  // Making $tagmap static as this function is called many times and
  // adds duplicate markup for each tag code in Drupal.settings JS,
  // so in media_process_form it adds something like tagCode:<markup>,
  // <markup> and when we replace in attach see two duplicate images
  // for one tagCode. Making static would make function remember value
  // between function calls. Since media_process_form is multiple times
  // with same form, this function is also called multiple times.
  static $tagmap = array();
  preg_match_all("/\[block_insert\].*?\[\/block_insert\]/s", $text, $matches, PREG_SET_ORDER);
  foreach ($matches as $match) {
    $bid = substr($match[0], strlen('[block_insert]'), strlen($match[0]) - strlen('[block_insert]') - strlen('[/block_insert]'));;
    // We see if tagContent is already in $tagMap, if not we add it
    // to $tagmap.  If we return an empty array, we break embeddings of the same
    // media multiple times.
    if (empty($tagmap[$match[0]])) {
      if ($markup = bean_wysiwyg_token_to_markup($match)) {
        $markup = '<div class="block-insert" data-block_insert="' . $bid . '" contenteditable="false">' . $markup . '<!-- block-insert --></div>';
        $tagmap[$match[0]] = $markup;
      }
      else {
        $missing = file_create_url(drupal_get_path('module', 'media') . '/images/icons/default/image-x-generic.png');
        $tagmap[$match[0]] = '<div><img src="' . $missing . '" width="100px" height="100px"/></div>';
      }
    }
  }
  return $tagmap;
}

/**
 * Recursively strip all contextual links in the element.
 */
function _bean_wysiwyg_strip_contextual_links(&$element) {
  if (!is_array($element)) {
    return;
  }

  if (isset($element['#contextual_links'])) {
    unset($element['#contextual_links']);
  }

  foreach (element_children($element) as $key) {
    _bean_wysiwyg_strip_contextual_links($element[$key]);
  }
}